services:
  - type: web
    name: aplikasi-stok-kerabat
    runtime: node
    rootDir: ./
    plan: free
    buildCommand: npm install && npm run build --workspace=backend
    startCommand: npm run start --workspace=backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: BETTER_AUTH_URL
        value: https://aplikasi-stok-kerabat.onrender.com/api/auth
      - key: FRONTEND_URL
        value: https://aplikasi-stok-kerabat-pos.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
