import { Router } from 'express';
import { AttendanceController } from '../controllers/attendance.controller.js';
import { requireAdmin, requireAuth } from '../middleware/auth.js';
import { validateBase64Image } from '../middleware/validateImage.js';
const router = Router();
router.get('/today', requireAuth, AttendanceController.getTodayStatus);
router.post('/check-in', requireAuth, validateBase64Image('photo'), AttendanceController.checkIn);
router.post('/check-out', requireAuth, validateBase64Image('photo'), AttendanceController.checkOut);
router.get('/history', requireAdmin, AttendanceController.getHistory);
router.get('/view-once/:filename', requireAdmin, AttendanceController.viewOnce);
router.delete('/bulk-delete', requireAdmin, AttendanceController.deleteByRange);
router.delete('/:id', requireAdmin, AttendanceController.deleteRecord);
export { router as attendanceRoutes };
